### PR TITLE
Add support for Swift 5.7

### PR DESCRIPTION
**Pull request by RemiBardon**

### CODE REVIEW

**Comment by RemiBardon** [comment]
Hmm… it doesn't seem to work. After a `make intall` and a run on a `swift-tools-version:5.6` package, I get:

```log
SitrepCore/File.swift:36: Fatal error: Swift has reported a version incompatibility that's causing problems.
This usually means Sitrep was built using a different version of Swift
than the one currently enabled on your system. I wish this was handled
more gracefully, but I'm afraid SwiftSyntax – the Apple library used by
Sitrep – is rather flaky in this way.

For reference, Sitrep is currently designed to work with Swift 5.4, 5.5, 5.6 and 5.7.
[1]    94995 illegal hardware instruction  sitrep
```

**Comment by twostraws** [comment]
I'm looking into this now. It looks like SwiftSyntax is stable from 5.8, so I'm going to move Sitrep up to support that as a minimum – hopefully this means breakage will be less common going forwards.
